/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sincronizador;

import logic.Routes;
import bean.Response;
import bean.Catalog;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logic.Api;
import javax.swing.JOptionPane;
import org.json.JSONException;

/**
 *
 * @author lti
 */
public class AppCatalog extends javax.swing.JFrame {
    private Routes r;
    /**
     * Creates new form Catalogo
     */
    public AppCatalog() {
        try {
            r = new Routes();
            initComponents();
        } catch (IOException ex) {
            Logger.getLogger(AppAuth.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namcatalog_txt = new javax.swing.JTextField();
        single = new javax.swing.JRadioButton();
        ida = new javax.swing.JRadioButton();
        activado = new javax.swing.JRadioButton();
        desactivado = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setForeground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Nombre del Catálogo:");

        buttonGroup1.add(single);
        single.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        single.setForeground(new java.awt.Color(1, 1, 1));
        single.setSelected(true);
        single.setText("SINGLE");
        single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleActionPerformed(evt);
            }
        });

        buttonGroup1.add(ida);
        ida.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        ida.setForeground(new java.awt.Color(3, 3, 3));
        ida.setText("IDA");
        ida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idaActionPerformed(evt);
            }
        });

        buttonGroup2.add(activado);
        activado.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        activado.setForeground(new java.awt.Color(1, 1, 1));
        activado.setSelected(true);
        activado.setText("Activado");
        activado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activadoActionPerformed(evt);
            }
        });

        buttonGroup2.add(desactivado);
        desactivado.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        desactivado.setForeground(new java.awt.Color(1, 1, 1));
        desactivado.setText("Desactivado");
        desactivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Seleccione modo de dispersión:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Cifrado:");

        jButton1.setText("Guardar Catalogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(single)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activado)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(namcatalog_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 321, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desactivado)
                        .addGap(103, 103, 103))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namcatalog_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(single)
                    .addComponent(activado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ida)
                    .addComponent(desactivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        namcatalog_txt.getAccessibleContext().setAccessibleName("namecatalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = namcatalog_txt.getText();
        String dispersemode = "";
        if (single.isSelected()) {
            dispersemode = "SINGLE";
        } else if (ida.isSelected()) {
            dispersemode = "IDA";
        }
        boolean encrypt = true;
        if (activado.isSelected()) {
            encrypt = true;
        } else if (desactivado.isSelected()) {
            encrypt = false;
        }

        Catalog c = new Catalog();
        c.setName(name);
        c.setDispersemode(dispersemode);
        c.setEncryption(encrypt);
        c.setFather("/");

        Api api = new Api();
        /*Response res = api._createCatalog(r.getGatewayRoute(), App.objUser, c);
        

        if (res.getCode() == 201) {
            JOptionPane.showMessageDialog(this, "Catálogo " + name + " creado!");
            File folder = new File(App.objUser.getUsername() + "/" + name);
            if (!folder.exists()) {
                folder.mkdir();
            }
            this.hide();
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear el catálogo");
        }*/

        namcatalog_txt.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void desactivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivadoActionPerformed
        // TODO add your handling code here:
        /*if (desactivado.isSelected()) {
            //single.setVisible(true);
            ida.setVisible(true);
            activado.setVisible(false);
            single.setSelected(true);
        }*/
    }//GEN-LAST:event_desactivadoActionPerformed

    private void activadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activadoActionPerformed
        // TODO add your handling code here:
        /*if (activado.isSelected()) {
            //single.setVisible(true);
            ida.setVisible(true);
            single.setVisible(true);
            desactivado.setSelected(false);
        }*/
    }//GEN-LAST:event_activadoActionPerformed

    private void idaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idaActionPerformed
        // TODO add your handling code here:
        /*if (ida.isSelected()) {
            //single.setVisible(true);
            single.setVisible(false);
            activado.setVisible(true);
            desactivado.setSelected(true);
        } */
    }//GEN-LAST:event_idaActionPerformed

    private void singleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleActionPerformed
        // TODO add your handling code here:
        /*if (single.isSelected()) {
            //single.setVisible(true);
            ida.setVisible(false);
            activado.setVisible(true);
            desactivado.setSelected(true);
            */
    }//GEN-LAST:event_singleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCatalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton desactivado;
    private javax.swing.JRadioButton ida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namcatalog_txt;
    private javax.swing.JRadioButton single;
    // End of variables declaration//GEN-END:variables


}
